#' 
#' @title Convert between feet NAVD88 and feet NGVD29
#' 
#' @description a raster surface of elevations NAVD88 rel to NGVD29. Units = feet. to convert NAVD88 to NGVD29, add this. subtract from NGVD29 to get NAVD88.
#'
#' @name convertNGVD
#' @format raster
#' @examples 
#' summary(convertNGVD)
#' 
#' \dontrun{
#' ### code used to generate object 
#' load("C:/RDATA/EVER4cast/NGVD_to_NAVD.RData") # loads convertNGVD, generated by script
#' writeRaster(convertNGVD, file = paste0(here::here(), "/inst/extdata/convertNGVD.grd"))
#' convertNGVD <- system.file("external/convertNGVD.grd", package="EvergladesEBM")
#' # save("convertNGVD", file =  paste0(here::here(), "/data/convertNGVD.RData"))
#' 
#' }
NULL